### ISSUE TITLE
Advice: Compatible encoding format for iOS and Android and disabling animation

### ISSUE THREAD

**Issue by codecoded** [SimformSolutionsPvtLtd/audio_waveforms#100]
Hi,

Firstly, great impressive plugin which I'm using for a chat app - but having a couple issues was hoping someone could help / advise

1. Is there a way to disable the animation? I have a list view that refreshes and sometimes the components rebuild, which triggers the animation. I've looked into several ways to try cache the widget, through keys and various other means, but ultimately, the animation really draws attention to the refresh. 

2. I commented on a closed issue, that I couldn't get the example code to work for iOS. I had to change the encoder format. I tried on iPhone 8 and 13 devices (iOS 15). I found the format that seems to be prmilary ok for iOS  is `kAudioFormatMPEG4AAC_HE_V2`. 

However, whilst the iOS file and it's waveform generates / display fine on Android when sent across the wire, playing it back it is silent. Android to iOS files play back fine. Is there a certain combination you know should work between the two different platforms or is some additional conversion required? I noticed missing / incorrect file extensions also can easily break the recording.

I was wondering should the `kAudioFormatMPEG4AAC ` format as used in your example code work fine on iOS? I find it odd that two devices would exhibit same, non-working behaviour in your example code implementation and also my own app without it being a known issue. 

Your help is much appreciated

**Comment by ujas-m-simformsolutions** [comment]
Hey @codecoded, 
1. If you are talking about waveforms from a file then you can just pass `Duration.zero` and it won't animate the waves.

2. I must have missed your comment so thanks for filing a new issue. Now, we have set the default value of encoder `kAudioFormatMPEG4AAC` because it's the default for ios, so it makes sense to just use that or you can try changing the default values of `sampleRate` and `bitRate`. We are going to change those default values to 44100 and 48000 in the next release so you can also try those values.

I wasn't aware about the ios -> android audio file doesn't playback so I will check that

**Comment by Ujas-Majithiya** [comment]
#103 this PR will fix waveforms not expanding when you provide `zero` duration and from your last update do audio files from ios to android play now if you use 44100 sample rate and 48000 bit rate?

**Comment by loic-hamdi** [comment]
> 2\. 44100

Thank you for the PR. Please update the documentation accordingly

**Comment by ujas-m-simformsolutions** [comment]
@codecoded and @loic-hamdi we have released `1.0.0` to pub.dev. In which, we have made bitRate nullable. So that platform can decide whatever bitRate is suitable. Mostly the bitRate parameter was interfering with other audio formats. So if you want to set bitRate then do make sure its right value.

Also we have updated how waveforms gets extracted so it should be more accurate now.

I'm going to close this issue for now. If you have any other issue feel free to create new issue.
