### ISSUE TITLE
iOS microphone is not working and Waveforms

### ISSUE THREAD

**Issue by nawafAlkhadidi** [SimformSolutionsPvtLtd/audio_waveforms#106]
> hi 

 ios microphone is not working and not display Waveforms

I checked the permissions and it works, I don't know where the problem is

I used the same code in another app and it works, but in my app it doesn't work

How can I solve this problem 

this image : 
[https://f.top4top.io/p_2459wnnyz1.png](url)

**Comment by ujas-m-simformsolutions** [comment]
@nawafAlkhadidi the image you have provided redirects to another site and can you try changing sampleRate to 44100 and bitrate to 48000

**Comment by Nico3652** [comment]
Hey @ujas-m-simformsolutions , 

I was also facing this issue since multiple days ago. 

I tried to copy/paste/run your **example** code but this not working, then i cloned your GitHub project and run but still not working. 

I also executed the same processes for Android and got the same result. 

On iOS when the microphone is opened there is a orange point on top like this :

![IMG_1794](https://user-images.githubusercontent.com/50270977/193308238-45d462a2-405c-4851-89d4-dbda39001de1.jpg)

And in this case the orange point is never displayed. So I think the problem is linked to micro call somehow but not with bitrate or other audio config

**Comment by nawafAlkhadidi** [comment]
this image : 
![Simulator Screen Shot - iPhone 14 Pro - 2022-09-25 at 13 46 46](https://user-images.githubusercontent.com/82181631/193797293-cef057ae-70f4-43f7-ac67-1ff8c0c4eb85.png)

**Comment by nawafAlkhadidi** [comment]
> 
I changed sample Rate to 44100 and bitrate to 48000
and then fixed it
thanks

**Comment by nawafAlkhadidi** [comment]
> @nawafAlkhadidi the image you have provided redirects to another site and can you try changing sampleRate to 44100 and bitrate to 48000

I changed sample Rate to 44100 and bitrate to 48000
and then fixed it
thanks
