### ISSUE TITLE
Smoothen wave progress animation

### ISSUE THREAD

**Issue by emrhnzngn** [SimformSolutionsPvtLtd/audio_waveforms#118]
I also need updateFrequency when playing audio how can I do it?

**Comment by ujas-m-simformsolutions** [comment]
This is currently not possible to do. Can you please elaborate more on what is your requirement?

**Comment by emrhnzngn** [comment]
I want the ripple effect to progress more smoothly after recording the sound, how can I do it?

**Comment by ujas-m-simformsolutions** [comment]
Oh, I see. That is actually not based on `updateFrequency` rather than it will require some different logic for updating the live wave. We will see this in the future if we are able to do this or not. Until then you can create a PR with the functionality you requested as we are open to any kind of contribution to this package.
