### ISSUE TITLE
Determine when Audio finished playing.

### ISSUE THREAD

**Issue by hagiosolat** [SimformSolutionsPvtLtd/audio_waveforms#137]
I made a chat app, I want to an event to be created automatically, like change the icon button when audio finished playing.
The available player states seems not to be enough to achieve that. 

I tried getting the  maxduration and currentduration. the completeduration for currentduration is not thesame for each time i play thesame video. Thus, to compare the two values is not possible to work out.

Anyway out?

**Comment by ujas-m-simformsolutions** [comment]
Hello @hagiosolat, Right now we don't have a completion listener. Comparing current and max duration sometimes won't work because `onCurrentDurationChanged` gets updated every 200ms. But if you are using `FinishMode.stop` or `FinishMode.pause` then current duration should be equal to max duration. But for looping we would need a completion listener.

**Comment by ujas-m-simformsolutions** [comment]
Moving it to enhancement this will be available next release.
