### ISSUE TITLE
wave format as previous version

### ISSUE THREAD

**Issue by csacchetti** [SimformSolutionsPvtLtd/audio_waveforms#159]
Since there are plans to put the option to use the audio wave format as in the previous version, as this may seem too uniform, I was asking when you plan to add it. I ask this because I have the app ready to go and if the timeframe is very long, I will put the old version of the plugin in, otherwise I will wait for the change.
Thank you for your valuable work.

**Comment by ujas-m-simformsolutions** [comment]
Actually that functionality is merged into `main` branch and we haven't released it yet because we tend to release a new release if multiple features have been added. Right now I'm working on a different feature and it's half done. And after it gets completed we will release a new version. It might take me couple of days to complete it.

If you want you can directly use the main branch in your pubspec.yaml file and then `RecorderController` has new parameter in its constructor just enable it `RecorderController(useLegacyNormalization: true)` and use it as earlier you were using.

**Comment by csacchetti** [comment]
Thanks again. I can wait a few days, so I think I will wait for the new release.

**Comment by ujas-m-simformsolutions** [comment]
Hey @csacchetti new version has been released.

**Comment by csacchetti** [comment]
Thank you very much. Excellent result. Balancing scaleFactor and normalisationFactor gives good results. In my opinion better than the default version.
