### ISSUE TITLE
Failed to stop recording

### ISSUE THREAD

**Issue by hatemragab** [SimformSolutionsPvtLtd/audio_waveforms#163]
i have upgraded from v 1.0.1 to v 1.0.2 i have and when the call stop 
Failed to stop recording
Android 
first call for this ``` final path = await recorder.stop();``` works good when i try to record again and stop it not working

**Comment by Colton127** [comment]
I am experiencing the same issue.

**Comment by dimasnurab** [comment]
same issue

**Comment by burningdeep** [comment]
same here

**Comment by annt99** [comment]
same issue

**Comment by reliance-engineer** [comment]
same here

**Comment by hatemragab** [comment]
And the big problem is when back to Old version it wasn't working 😅

**Comment by reliance-engineer** [comment]
I've found that the problem happens after I call `controller.dispose()`, even if I create a new one I can't stop recording anymore

**Comment by Ujas-Majithiya** [comment]
Thanks for reporting this issue. I will look into this on Monday. Until then you might wanna use version 1.0.1. In pubspec, if you have '^' ahead of version then remove it. It will still consider latest minor version if you have added '^'.

**Comment by ujas-m-simformsolutions** [comment]
@hatemragab Can you please share which flutter version you are using and reproducible code because I tried on android device and I can't reproduce it.

**Comment by hatemragab** [comment]
I use current most stable version

**Comment by Ujas-Majithiya** [comment]
Can you share which device you are using?

**Comment by hatemragab** [comment]
i have try it in some of android devices like Poco f3 and Samsung

**Comment by ujas-m-simformsolutions** [comment]
From initial comment it looks like `stop` function is not working but I am not being able to reproduce this. If anyone can share reproducible steps then we might able fix this.

**Comment by hatemragab** [comment]
Ok i will share example

**Comment by NiklasFoP** [comment]
I have the same issue that it throws "Failed stop recording". It worked the very first time I used the package but now it never works again. I went back to 1.0.1 but then my app isn't even build anymore due some other issues.

**Comment by NiklasFoP** [comment]
> 

Here's some more information on the error: E/CheckPermission(32117): media_record-code= 1
D/MediaRecorder(32117): Release X 0xb4000078d8d17280
D/MediaRecorder(32117): destructor E 0xb4000078d8d17280
D/MediaRecorder(32117): destructor X 0xb4000078d8d17280
E/AudioWaveforms(32117): Failed to stop recording

When I go out of the widget by navigating in the app I get this among a lot of other messages that keep repeating and won't stop:
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

**Comment by AppetiteTeam** [comment]
same

**Comment by ujas-m-simformsolutions** [comment]
Thank you @NiklasFoP, I can reproduce the issue now.

**Comment by ujas-m-simformsolutions** [comment]
We have released `1.0.3` with a fix for this. If anyone still faces the issue please file a new issue.
