### ISSUE TITLE
E/AudioWaveforms(17220): Microphone might be turned off

### ISSUE THREAD

**Issue by MapperMalte** [SimformSolutionsPvtLtd/audio_waveforms#25]
Thank you for this package.
I am getting this error message repeatedly when trying out the example code.
However, it seems to work fine. The WaveForm appears to show the negative of the input. When I record, it gets small, when I am silent, it is at max.

Best regards!

**Comment by ujas-m-simformsolutions** [comment]
If you are using an android emulators to test then android emulators doesn't pick up microphone sometimes so it does not provide any audio data so that's why you are getting that warning.

Now for your second question, have you changed anything on the example app if yes then can you share the code. If not then can you share what device you were using. And also You can use the `normalizationFactor` available in the `WaveController` to normalise wave height according to your need.

Also if it's bug then can you share some initial values from` waveData` available in the controller.

**Comment by ujas-m-simformsolutions** [comment]
`WaveController` is now renamed to `RecorderController`

**Comment by ujas-m-simformsolutions** [comment]
@MapperMalte are you still facing this issue?

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue as no updates were provided.
