### ISSUE TITLE
How to keep playing the audio file when the app is in background in iOS?

### ISSUE THREAD

**Issue by HamzaMihfad** [SimformSolutionsPvtLtd/audio_waveforms#354]
When the app is in background or closed, the player stops playing in **iOS**

**Comment by Ujas-Majithiya** [comment]
@HamzaMihfad Playing audio background is out of the scope this plugin but you can achieve this easily like this,

firstly, you will need to enable the background mode `Audio, AirPlay, and Picture in Picture` from Xcode. Secondly, you will need to set your native AudioSession,
```swift
try AVAudioSession.sharedInstance().setCategory(.playback)
let _ = try AVAudioSession.sharedInstance().setActive(true)
```
Now, since this is native code you can use a flutter plugin to do this. A quick google search found me this [audio_session ](https://pub.dev/packages/audio_session).

I'm going close this but feel free to create a new issue if you face any problems.
